spring:
  application:
    name: dubbo-api
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false

mybatis:
  basepackage: com.dubbo.api.dao
  mapper-locations: "classpath*:mapper/*.xml"

logging:
  level:
    com.dubbo.api.dao: DEBUG

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

