spring:
  application:
    name: dubbo-api
  messages:
    basename: i18n/messages
    encoding: UTF-8

mybatis:
  basepackage: com.dubbo.api.dao
  mapper-locations: "classpath*:mapper/*.xml"

logging:
  level:
    com.dubbo.api.dao: INFO

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

