spring:
  application:
    name: dubbo-api
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/okay_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

server:
  port: 8901

mybatis:
  basepackage: com.dubbo.api.dao
  mapper-locations: "classpath*:mapper/*.xml"

